name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: |
          deno lint --rules-exclude='no-explicit-any','require-await','no-unused-vars' --fix
          deno run --allow-env --allow-net --allow-read --allow-write manage.ts collectstatic

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "atzufuki-myapp-25"
          entrypoint: "manage.ts"
          root: "."
